// cpu.v

// Generated using ACDS version 17.1 590

`timescale 1 ps / 1 ps
module cpu (
		input  wire        clk_clk,            //           clk.clk
		output wire        fifo_out_valid,     //      fifo_out.valid
		output wire [31:0] fifo_out_data,      //              .data
		output wire [7:0]  fifo_out_channel,   //              .channel
		output wire [7:0]  fifo_out_error,     //              .error
		input  wire        fifo_out_ready,     //              .ready
		input  wire        fifo_read_clk_clk,  // fifo_read_clk.clk
		input  wire        reset_reset_n,      //         reset.reset_n
		inout  wire        sd_card_b_SD_cmd,   //       sd_card.b_SD_cmd
		inout  wire        sd_card_b_SD_dat,   //              .b_SD_dat
		inout  wire        sd_card_b_SD_dat3,  //              .b_SD_dat3
		output wire        sd_card_o_SD_clock  //              .o_SD_clock
	);

	wire  [31:0] cpu_data_master_readdata;                                 // mm_interconnect_0:CPU_data_master_readdata -> CPU:d_readdata
	wire         cpu_data_master_waitrequest;                              // mm_interconnect_0:CPU_data_master_waitrequest -> CPU:d_waitrequest
	wire         cpu_data_master_debugaccess;                              // CPU:debug_mem_slave_debugaccess_to_roms -> mm_interconnect_0:CPU_data_master_debugaccess
	wire  [18:0] cpu_data_master_address;                                  // CPU:d_address -> mm_interconnect_0:CPU_data_master_address
	wire   [3:0] cpu_data_master_byteenable;                               // CPU:d_byteenable -> mm_interconnect_0:CPU_data_master_byteenable
	wire         cpu_data_master_read;                                     // CPU:d_read -> mm_interconnect_0:CPU_data_master_read
	wire         cpu_data_master_write;                                    // CPU:d_write -> mm_interconnect_0:CPU_data_master_write
	wire  [31:0] cpu_data_master_writedata;                                // CPU:d_writedata -> mm_interconnect_0:CPU_data_master_writedata
	wire  [31:0] cpu_instruction_master_readdata;                          // mm_interconnect_0:CPU_instruction_master_readdata -> CPU:i_readdata
	wire         cpu_instruction_master_waitrequest;                       // mm_interconnect_0:CPU_instruction_master_waitrequest -> CPU:i_waitrequest
	wire  [18:0] cpu_instruction_master_address;                           // CPU:i_address -> mm_interconnect_0:CPU_instruction_master_address
	wire         cpu_instruction_master_read;                              // CPU:i_read -> mm_interconnect_0:CPU_instruction_master_read
	wire         mm_interconnect_0_debug_avalon_jtag_slave_chipselect;     // mm_interconnect_0:DEBUG_avalon_jtag_slave_chipselect -> DEBUG:av_chipselect
	wire  [31:0] mm_interconnect_0_debug_avalon_jtag_slave_readdata;       // DEBUG:av_readdata -> mm_interconnect_0:DEBUG_avalon_jtag_slave_readdata
	wire         mm_interconnect_0_debug_avalon_jtag_slave_waitrequest;    // DEBUG:av_waitrequest -> mm_interconnect_0:DEBUG_avalon_jtag_slave_waitrequest
	wire   [0:0] mm_interconnect_0_debug_avalon_jtag_slave_address;        // mm_interconnect_0:DEBUG_avalon_jtag_slave_address -> DEBUG:av_address
	wire         mm_interconnect_0_debug_avalon_jtag_slave_read;           // mm_interconnect_0:DEBUG_avalon_jtag_slave_read -> DEBUG:av_read_n
	wire         mm_interconnect_0_debug_avalon_jtag_slave_write;          // mm_interconnect_0:DEBUG_avalon_jtag_slave_write -> DEBUG:av_write_n
	wire  [31:0] mm_interconnect_0_debug_avalon_jtag_slave_writedata;      // mm_interconnect_0:DEBUG_avalon_jtag_slave_writedata -> DEBUG:av_writedata
	wire         mm_interconnect_0_sdcard_avalon_sdcard_slave_chipselect;  // mm_interconnect_0:SDCard_avalon_sdcard_slave_chipselect -> SDCard:i_avalon_chip_select
	wire  [31:0] mm_interconnect_0_sdcard_avalon_sdcard_slave_readdata;    // SDCard:o_avalon_readdata -> mm_interconnect_0:SDCard_avalon_sdcard_slave_readdata
	wire         mm_interconnect_0_sdcard_avalon_sdcard_slave_waitrequest; // SDCard:o_avalon_waitrequest -> mm_interconnect_0:SDCard_avalon_sdcard_slave_waitrequest
	wire   [7:0] mm_interconnect_0_sdcard_avalon_sdcard_slave_address;     // mm_interconnect_0:SDCard_avalon_sdcard_slave_address -> SDCard:i_avalon_address
	wire         mm_interconnect_0_sdcard_avalon_sdcard_slave_read;        // mm_interconnect_0:SDCard_avalon_sdcard_slave_read -> SDCard:i_avalon_read
	wire   [3:0] mm_interconnect_0_sdcard_avalon_sdcard_slave_byteenable;  // mm_interconnect_0:SDCard_avalon_sdcard_slave_byteenable -> SDCard:i_avalon_byteenable
	wire         mm_interconnect_0_sdcard_avalon_sdcard_slave_write;       // mm_interconnect_0:SDCard_avalon_sdcard_slave_write -> SDCard:i_avalon_write
	wire  [31:0] mm_interconnect_0_sdcard_avalon_sdcard_slave_writedata;   // mm_interconnect_0:SDCard_avalon_sdcard_slave_writedata -> SDCard:i_avalon_writedata
	wire  [31:0] mm_interconnect_0_cpu_debug_mem_slave_readdata;           // CPU:debug_mem_slave_readdata -> mm_interconnect_0:CPU_debug_mem_slave_readdata
	wire         mm_interconnect_0_cpu_debug_mem_slave_waitrequest;        // CPU:debug_mem_slave_waitrequest -> mm_interconnect_0:CPU_debug_mem_slave_waitrequest
	wire         mm_interconnect_0_cpu_debug_mem_slave_debugaccess;        // mm_interconnect_0:CPU_debug_mem_slave_debugaccess -> CPU:debug_mem_slave_debugaccess
	wire   [8:0] mm_interconnect_0_cpu_debug_mem_slave_address;            // mm_interconnect_0:CPU_debug_mem_slave_address -> CPU:debug_mem_slave_address
	wire         mm_interconnect_0_cpu_debug_mem_slave_read;               // mm_interconnect_0:CPU_debug_mem_slave_read -> CPU:debug_mem_slave_read
	wire   [3:0] mm_interconnect_0_cpu_debug_mem_slave_byteenable;         // mm_interconnect_0:CPU_debug_mem_slave_byteenable -> CPU:debug_mem_slave_byteenable
	wire         mm_interconnect_0_cpu_debug_mem_slave_write;              // mm_interconnect_0:CPU_debug_mem_slave_write -> CPU:debug_mem_slave_write
	wire  [31:0] mm_interconnect_0_cpu_debug_mem_slave_writedata;          // mm_interconnect_0:CPU_debug_mem_slave_writedata -> CPU:debug_mem_slave_writedata
	wire         mm_interconnect_0_fifo_in_waitrequest;                    // FIFO:avalonmm_write_slave_waitrequest -> mm_interconnect_0:FIFO_in_waitrequest
	wire   [0:0] mm_interconnect_0_fifo_in_address;                        // mm_interconnect_0:FIFO_in_address -> FIFO:avalonmm_write_slave_address
	wire         mm_interconnect_0_fifo_in_write;                          // mm_interconnect_0:FIFO_in_write -> FIFO:avalonmm_write_slave_write
	wire  [31:0] mm_interconnect_0_fifo_in_writedata;                      // mm_interconnect_0:FIFO_in_writedata -> FIFO:avalonmm_write_slave_writedata
	wire  [31:0] mm_interconnect_0_fifo_in_csr_readdata;                   // FIFO:wrclk_control_slave_readdata -> mm_interconnect_0:FIFO_in_csr_readdata
	wire   [2:0] mm_interconnect_0_fifo_in_csr_address;                    // mm_interconnect_0:FIFO_in_csr_address -> FIFO:wrclk_control_slave_address
	wire         mm_interconnect_0_fifo_in_csr_read;                       // mm_interconnect_0:FIFO_in_csr_read -> FIFO:wrclk_control_slave_read
	wire         mm_interconnect_0_fifo_in_csr_write;                      // mm_interconnect_0:FIFO_in_csr_write -> FIFO:wrclk_control_slave_write
	wire  [31:0] mm_interconnect_0_fifo_in_csr_writedata;                  // mm_interconnect_0:FIFO_in_csr_writedata -> FIFO:wrclk_control_slave_writedata
	wire  [31:0] mm_interconnect_0_fifo_out_csr_readdata;                  // FIFO:rdclk_control_slave_readdata -> mm_interconnect_0:FIFO_out_csr_readdata
	wire   [2:0] mm_interconnect_0_fifo_out_csr_address;                   // mm_interconnect_0:FIFO_out_csr_address -> FIFO:rdclk_control_slave_address
	wire         mm_interconnect_0_fifo_out_csr_read;                      // mm_interconnect_0:FIFO_out_csr_read -> FIFO:rdclk_control_slave_read
	wire         mm_interconnect_0_fifo_out_csr_write;                     // mm_interconnect_0:FIFO_out_csr_write -> FIFO:rdclk_control_slave_write
	wire  [31:0] mm_interconnect_0_fifo_out_csr_writedata;                 // mm_interconnect_0:FIFO_out_csr_writedata -> FIFO:rdclk_control_slave_writedata
	wire         mm_interconnect_0_ram_s1_chipselect;                      // mm_interconnect_0:RAM_s1_chipselect -> RAM:chipselect
	wire  [31:0] mm_interconnect_0_ram_s1_readdata;                        // RAM:readdata -> mm_interconnect_0:RAM_s1_readdata
	wire  [14:0] mm_interconnect_0_ram_s1_address;                         // mm_interconnect_0:RAM_s1_address -> RAM:address
	wire   [3:0] mm_interconnect_0_ram_s1_byteenable;                      // mm_interconnect_0:RAM_s1_byteenable -> RAM:byteenable
	wire         mm_interconnect_0_ram_s1_write;                           // mm_interconnect_0:RAM_s1_write -> RAM:write
	wire  [31:0] mm_interconnect_0_ram_s1_writedata;                       // mm_interconnect_0:RAM_s1_writedata -> RAM:writedata
	wire         mm_interconnect_0_ram_s1_clken;                           // mm_interconnect_0:RAM_s1_clken -> RAM:clken
	wire         irq_mapper_receiver0_irq;                                 // DEBUG:av_irq -> irq_mapper:receiver0_irq
	wire  [31:0] cpu_irq_irq;                                              // irq_mapper:sender_irq -> CPU:irq
	wire         rst_controller_reset_out_reset;                           // rst_controller:reset_out -> [CPU:reset_n, DEBUG:rst_n, FIFO:wrreset_n, RAM:reset, SDCard:i_reset_n, irq_mapper:reset, mm_interconnect_0:CPU_reset_reset_bridge_in_reset_reset, rst_translator:in_reset]
	wire         rst_controller_reset_out_reset_req;                       // rst_controller:reset_req -> [CPU:reset_req, RAM:reset_req, rst_translator:reset_req_in]
	wire         rst_controller_001_reset_out_reset;                       // rst_controller_001:reset_out -> [FIFO:rdreset_n, mm_interconnect_0:FIFO_reset_out_reset_bridge_in_reset_reset]

	cpu_CPU cpu (
		.clk                                 (clk_clk),                                           //                       clk.clk
		.reset_n                             (~rst_controller_reset_out_reset),                   //                     reset.reset_n
		.reset_req                           (rst_controller_reset_out_reset_req),                //                          .reset_req
		.d_address                           (cpu_data_master_address),                           //               data_master.address
		.d_byteenable                        (cpu_data_master_byteenable),                        //                          .byteenable
		.d_read                              (cpu_data_master_read),                              //                          .read
		.d_readdata                          (cpu_data_master_readdata),                          //                          .readdata
		.d_waitrequest                       (cpu_data_master_waitrequest),                       //                          .waitrequest
		.d_write                             (cpu_data_master_write),                             //                          .write
		.d_writedata                         (cpu_data_master_writedata),                         //                          .writedata
		.debug_mem_slave_debugaccess_to_roms (cpu_data_master_debugaccess),                       //                          .debugaccess
		.i_address                           (cpu_instruction_master_address),                    //        instruction_master.address
		.i_read                              (cpu_instruction_master_read),                       //                          .read
		.i_readdata                          (cpu_instruction_master_readdata),                   //                          .readdata
		.i_waitrequest                       (cpu_instruction_master_waitrequest),                //                          .waitrequest
		.irq                                 (cpu_irq_irq),                                       //                       irq.irq
		.debug_reset_request                 (),                                                  //       debug_reset_request.reset
		.debug_mem_slave_address             (mm_interconnect_0_cpu_debug_mem_slave_address),     //           debug_mem_slave.address
		.debug_mem_slave_byteenable          (mm_interconnect_0_cpu_debug_mem_slave_byteenable),  //                          .byteenable
		.debug_mem_slave_debugaccess         (mm_interconnect_0_cpu_debug_mem_slave_debugaccess), //                          .debugaccess
		.debug_mem_slave_read                (mm_interconnect_0_cpu_debug_mem_slave_read),        //                          .read
		.debug_mem_slave_readdata            (mm_interconnect_0_cpu_debug_mem_slave_readdata),    //                          .readdata
		.debug_mem_slave_waitrequest         (mm_interconnect_0_cpu_debug_mem_slave_waitrequest), //                          .waitrequest
		.debug_mem_slave_write               (mm_interconnect_0_cpu_debug_mem_slave_write),       //                          .write
		.debug_mem_slave_writedata           (mm_interconnect_0_cpu_debug_mem_slave_writedata),   //                          .writedata
		.dummy_ci_port                       ()                                                   // custom_instruction_master.readra
	);

	cpu_DEBUG debug (
		.clk            (clk_clk),                                               //               clk.clk
		.rst_n          (~rst_controller_reset_out_reset),                       //             reset.reset_n
		.av_chipselect  (mm_interconnect_0_debug_avalon_jtag_slave_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (mm_interconnect_0_debug_avalon_jtag_slave_address),     //                  .address
		.av_read_n      (~mm_interconnect_0_debug_avalon_jtag_slave_read),       //                  .read_n
		.av_readdata    (mm_interconnect_0_debug_avalon_jtag_slave_readdata),    //                  .readdata
		.av_write_n     (~mm_interconnect_0_debug_avalon_jtag_slave_write),      //                  .write_n
		.av_writedata   (mm_interconnect_0_debug_avalon_jtag_slave_writedata),   //                  .writedata
		.av_waitrequest (mm_interconnect_0_debug_avalon_jtag_slave_waitrequest), //                  .waitrequest
		.av_irq         (irq_mapper_receiver0_irq)                               //               irq.irq
	);

	cpu_FIFO fifo (
		.wrclock                          (clk_clk),                                  //    clk_in.clk
		.wrreset_n                        (~rst_controller_reset_out_reset),          //  reset_in.reset_n
		.rdclock                          (fifo_read_clk_clk),                        //   clk_out.clk
		.rdreset_n                        (~rst_controller_001_reset_out_reset),      // reset_out.reset_n
		.avalonmm_write_slave_writedata   (mm_interconnect_0_fifo_in_writedata),      //        in.writedata
		.avalonmm_write_slave_write       (mm_interconnect_0_fifo_in_write),          //          .write
		.avalonmm_write_slave_address     (mm_interconnect_0_fifo_in_address),        //          .address
		.avalonmm_write_slave_waitrequest (mm_interconnect_0_fifo_in_waitrequest),    //          .waitrequest
		.avalonst_source_valid            (fifo_out_valid),                           //       out.valid
		.avalonst_source_data             (fifo_out_data),                            //          .data
		.avalonst_source_channel          (fifo_out_channel),                         //          .channel
		.avalonst_source_error            (fifo_out_error),                           //          .error
		.avalonst_source_ready            (fifo_out_ready),                           //          .ready
		.rdclk_control_slave_address      (mm_interconnect_0_fifo_out_csr_address),   //   out_csr.address
		.rdclk_control_slave_read         (mm_interconnect_0_fifo_out_csr_read),      //          .read
		.rdclk_control_slave_writedata    (mm_interconnect_0_fifo_out_csr_writedata), //          .writedata
		.rdclk_control_slave_write        (mm_interconnect_0_fifo_out_csr_write),     //          .write
		.rdclk_control_slave_readdata     (mm_interconnect_0_fifo_out_csr_readdata),  //          .readdata
		.wrclk_control_slave_address      (mm_interconnect_0_fifo_in_csr_address),    //    in_csr.address
		.wrclk_control_slave_read         (mm_interconnect_0_fifo_in_csr_read),       //          .read
		.wrclk_control_slave_writedata    (mm_interconnect_0_fifo_in_csr_writedata),  //          .writedata
		.wrclk_control_slave_write        (mm_interconnect_0_fifo_in_csr_write),      //          .write
		.wrclk_control_slave_readdata     (mm_interconnect_0_fifo_in_csr_readdata)    //          .readdata
	);

	cpu_RAM ram (
		.clk        (clk_clk),                             //   clk1.clk
		.address    (mm_interconnect_0_ram_s1_address),    //     s1.address
		.clken      (mm_interconnect_0_ram_s1_clken),      //       .clken
		.chipselect (mm_interconnect_0_ram_s1_chipselect), //       .chipselect
		.write      (mm_interconnect_0_ram_s1_write),      //       .write
		.readdata   (mm_interconnect_0_ram_s1_readdata),   //       .readdata
		.writedata  (mm_interconnect_0_ram_s1_writedata),  //       .writedata
		.byteenable (mm_interconnect_0_ram_s1_byteenable), //       .byteenable
		.reset      (rst_controller_reset_out_reset),      // reset1.reset
		.reset_req  (rst_controller_reset_out_reset_req),  //       .reset_req
		.freeze     (1'b0)                                 // (terminated)
	);

	Altera_UP_SD_Card_Avalon_Interface sdcard (
		.i_avalon_chip_select (mm_interconnect_0_sdcard_avalon_sdcard_slave_chipselect),  // avalon_sdcard_slave.chipselect
		.i_avalon_address     (mm_interconnect_0_sdcard_avalon_sdcard_slave_address),     //                    .address
		.i_avalon_read        (mm_interconnect_0_sdcard_avalon_sdcard_slave_read),        //                    .read
		.i_avalon_write       (mm_interconnect_0_sdcard_avalon_sdcard_slave_write),       //                    .write
		.i_avalon_byteenable  (mm_interconnect_0_sdcard_avalon_sdcard_slave_byteenable),  //                    .byteenable
		.i_avalon_writedata   (mm_interconnect_0_sdcard_avalon_sdcard_slave_writedata),   //                    .writedata
		.o_avalon_readdata    (mm_interconnect_0_sdcard_avalon_sdcard_slave_readdata),    //                    .readdata
		.o_avalon_waitrequest (mm_interconnect_0_sdcard_avalon_sdcard_slave_waitrequest), //                    .waitrequest
		.i_clock              (clk_clk),                                                  //                 clk.clk
		.i_reset_n            (~rst_controller_reset_out_reset),                          //               reset.reset_n
		.b_SD_cmd             (sd_card_b_SD_cmd),                                         //         conduit_end.export
		.b_SD_dat             (sd_card_b_SD_dat),                                         //                    .export
		.b_SD_dat3            (sd_card_b_SD_dat3),                                        //                    .export
		.o_SD_clock           (sd_card_o_SD_clock)                                        //                    .export
	);

	cpu_mm_interconnect_0 mm_interconnect_0 (
		.clk_0_clk_clk                              (clk_clk),                                                  //                            clk_0_clk.clk
		.clock_bridge_0_out_clk_clk                 (fifo_read_clk_clk),                                        //               clock_bridge_0_out_clk.clk
		.CPU_reset_reset_bridge_in_reset_reset      (rst_controller_reset_out_reset),                           //      CPU_reset_reset_bridge_in_reset.reset
		.FIFO_reset_out_reset_bridge_in_reset_reset (rst_controller_001_reset_out_reset),                       // FIFO_reset_out_reset_bridge_in_reset.reset
		.CPU_data_master_address                    (cpu_data_master_address),                                  //                      CPU_data_master.address
		.CPU_data_master_waitrequest                (cpu_data_master_waitrequest),                              //                                     .waitrequest
		.CPU_data_master_byteenable                 (cpu_data_master_byteenable),                               //                                     .byteenable
		.CPU_data_master_read                       (cpu_data_master_read),                                     //                                     .read
		.CPU_data_master_readdata                   (cpu_data_master_readdata),                                 //                                     .readdata
		.CPU_data_master_write                      (cpu_data_master_write),                                    //                                     .write
		.CPU_data_master_writedata                  (cpu_data_master_writedata),                                //                                     .writedata
		.CPU_data_master_debugaccess                (cpu_data_master_debugaccess),                              //                                     .debugaccess
		.CPU_instruction_master_address             (cpu_instruction_master_address),                           //               CPU_instruction_master.address
		.CPU_instruction_master_waitrequest         (cpu_instruction_master_waitrequest),                       //                                     .waitrequest
		.CPU_instruction_master_read                (cpu_instruction_master_read),                              //                                     .read
		.CPU_instruction_master_readdata            (cpu_instruction_master_readdata),                          //                                     .readdata
		.CPU_debug_mem_slave_address                (mm_interconnect_0_cpu_debug_mem_slave_address),            //                  CPU_debug_mem_slave.address
		.CPU_debug_mem_slave_write                  (mm_interconnect_0_cpu_debug_mem_slave_write),              //                                     .write
		.CPU_debug_mem_slave_read                   (mm_interconnect_0_cpu_debug_mem_slave_read),               //                                     .read
		.CPU_debug_mem_slave_readdata               (mm_interconnect_0_cpu_debug_mem_slave_readdata),           //                                     .readdata
		.CPU_debug_mem_slave_writedata              (mm_interconnect_0_cpu_debug_mem_slave_writedata),          //                                     .writedata
		.CPU_debug_mem_slave_byteenable             (mm_interconnect_0_cpu_debug_mem_slave_byteenable),         //                                     .byteenable
		.CPU_debug_mem_slave_waitrequest            (mm_interconnect_0_cpu_debug_mem_slave_waitrequest),        //                                     .waitrequest
		.CPU_debug_mem_slave_debugaccess            (mm_interconnect_0_cpu_debug_mem_slave_debugaccess),        //                                     .debugaccess
		.DEBUG_avalon_jtag_slave_address            (mm_interconnect_0_debug_avalon_jtag_slave_address),        //              DEBUG_avalon_jtag_slave.address
		.DEBUG_avalon_jtag_slave_write              (mm_interconnect_0_debug_avalon_jtag_slave_write),          //                                     .write
		.DEBUG_avalon_jtag_slave_read               (mm_interconnect_0_debug_avalon_jtag_slave_read),           //                                     .read
		.DEBUG_avalon_jtag_slave_readdata           (mm_interconnect_0_debug_avalon_jtag_slave_readdata),       //                                     .readdata
		.DEBUG_avalon_jtag_slave_writedata          (mm_interconnect_0_debug_avalon_jtag_slave_writedata),      //                                     .writedata
		.DEBUG_avalon_jtag_slave_waitrequest        (mm_interconnect_0_debug_avalon_jtag_slave_waitrequest),    //                                     .waitrequest
		.DEBUG_avalon_jtag_slave_chipselect         (mm_interconnect_0_debug_avalon_jtag_slave_chipselect),     //                                     .chipselect
		.FIFO_in_address                            (mm_interconnect_0_fifo_in_address),                        //                              FIFO_in.address
		.FIFO_in_write                              (mm_interconnect_0_fifo_in_write),                          //                                     .write
		.FIFO_in_writedata                          (mm_interconnect_0_fifo_in_writedata),                      //                                     .writedata
		.FIFO_in_waitrequest                        (mm_interconnect_0_fifo_in_waitrequest),                    //                                     .waitrequest
		.FIFO_in_csr_address                        (mm_interconnect_0_fifo_in_csr_address),                    //                          FIFO_in_csr.address
		.FIFO_in_csr_write                          (mm_interconnect_0_fifo_in_csr_write),                      //                                     .write
		.FIFO_in_csr_read                           (mm_interconnect_0_fifo_in_csr_read),                       //                                     .read
		.FIFO_in_csr_readdata                       (mm_interconnect_0_fifo_in_csr_readdata),                   //                                     .readdata
		.FIFO_in_csr_writedata                      (mm_interconnect_0_fifo_in_csr_writedata),                  //                                     .writedata
		.FIFO_out_csr_address                       (mm_interconnect_0_fifo_out_csr_address),                   //                         FIFO_out_csr.address
		.FIFO_out_csr_write                         (mm_interconnect_0_fifo_out_csr_write),                     //                                     .write
		.FIFO_out_csr_read                          (mm_interconnect_0_fifo_out_csr_read),                      //                                     .read
		.FIFO_out_csr_readdata                      (mm_interconnect_0_fifo_out_csr_readdata),                  //                                     .readdata
		.FIFO_out_csr_writedata                     (mm_interconnect_0_fifo_out_csr_writedata),                 //                                     .writedata
		.RAM_s1_address                             (mm_interconnect_0_ram_s1_address),                         //                               RAM_s1.address
		.RAM_s1_write                               (mm_interconnect_0_ram_s1_write),                           //                                     .write
		.RAM_s1_readdata                            (mm_interconnect_0_ram_s1_readdata),                        //                                     .readdata
		.RAM_s1_writedata                           (mm_interconnect_0_ram_s1_writedata),                       //                                     .writedata
		.RAM_s1_byteenable                          (mm_interconnect_0_ram_s1_byteenable),                      //                                     .byteenable
		.RAM_s1_chipselect                          (mm_interconnect_0_ram_s1_chipselect),                      //                                     .chipselect
		.RAM_s1_clken                               (mm_interconnect_0_ram_s1_clken),                           //                                     .clken
		.SDCard_avalon_sdcard_slave_address         (mm_interconnect_0_sdcard_avalon_sdcard_slave_address),     //           SDCard_avalon_sdcard_slave.address
		.SDCard_avalon_sdcard_slave_write           (mm_interconnect_0_sdcard_avalon_sdcard_slave_write),       //                                     .write
		.SDCard_avalon_sdcard_slave_read            (mm_interconnect_0_sdcard_avalon_sdcard_slave_read),        //                                     .read
		.SDCard_avalon_sdcard_slave_readdata        (mm_interconnect_0_sdcard_avalon_sdcard_slave_readdata),    //                                     .readdata
		.SDCard_avalon_sdcard_slave_writedata       (mm_interconnect_0_sdcard_avalon_sdcard_slave_writedata),   //                                     .writedata
		.SDCard_avalon_sdcard_slave_byteenable      (mm_interconnect_0_sdcard_avalon_sdcard_slave_byteenable),  //                                     .byteenable
		.SDCard_avalon_sdcard_slave_waitrequest     (mm_interconnect_0_sdcard_avalon_sdcard_slave_waitrequest), //                                     .waitrequest
		.SDCard_avalon_sdcard_slave_chipselect      (mm_interconnect_0_sdcard_avalon_sdcard_slave_chipselect)   //                                     .chipselect
	);

	cpu_irq_mapper irq_mapper (
		.clk           (clk_clk),                        //       clk.clk
		.reset         (rst_controller_reset_out_reset), // clk_reset.reset
		.receiver0_irq (irq_mapper_receiver0_irq),       // receiver0.irq
		.sender_irq    (cpu_irq_irq)                     //    sender.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_reset_n),                     // reset_in0.reset
		.clk            (clk_clk),                            //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),     // reset_out.reset
		.reset_req      (rst_controller_reset_out_reset_req), //          .reset_req
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_001 (
		.reset_in0      (~reset_reset_n),                     // reset_in0.reset
		.clk            (fifo_read_clk_clk),                  //       clk.clk
		.reset_out      (rst_controller_001_reset_out_reset), // reset_out.reset
		.reset_req      (),                                   // (terminated)
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

endmodule
