// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Build 590 10/25/2017)
// Created on Wed Mar 04 11:03:38 2026

mel_20 mel_20_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.rst_n(rst_n_sig) ,	// input  rst_n_sig
	.rx_ready_in(rx_ready_in_sig) ,	// input  rx_ready_in_sig
	.bin_valid(bin_valid_sig) ,	// input  bin_valid_sig
	.bin_data(bin_data_sig) ,	// input [31:0] bin_data_sig
	.rx_done(rx_done_sig) ,	// output  rx_done_sig
	.start_calc(start_calc_sig) ,	// input  start_calc_sig
	.calc_done(calc_done_sig) ,	// output  calc_done_sig
	.rd_ready_in(rd_ready_in_sig) ,	// input  rd_ready_in_sig
	.mel_valid(mel_valid_sig) ,	// output  mel_valid_sig
	.mel_index(mel_index_sig) ,	// output [4:0] mel_index_sig
	.mel_out(mel_out_sig) ,	// output [47:0] mel_out_sig
	.read_done(read_done_sig) 	// output  read_done_sig
);

